#!/bin/sh

# Script made by the boomer of Luke Smith. 
# I made a little modification on the push notification. 
[ "$(stat -c %y /tmp/weatherreport | awk '{print $1}')" != "$(date '+%Y-%m-%d')" ] && getforecast

if [ $BLOCK_BUTTON ] && [ $BLOCK_BUTTON -eq 1 ]; then
  notify-send -u normal -t 4000 "$(cat /tmp/weatherreport | head -7 | tail -5 | sed 's/\x1b\[[0-9;]*m//g')"
fi

printf "%s" "$(sed '16q;d' /tmp/weatherreport | grep -wo "[0-9]*%" | sort -n | sed -e '$!d' | sed -e "s/^/☔ /g" | tr -d '\n')"

sed '13q;d' /tmp/weatherreport | grep -o "m\\(-\\)*[0-9]\\+" | sort -n -t 'm' -k 2n | sed -e 1b -e '$!d' | tr '\n|m' ' ' | awk '{print " ❄️",$1 "°","🌞",$2 "°"}'
